classDiagram
    class Глядач {
        +String ім'я
        +підписка()
        +перегляд()
    }

    class Автор {
        +String ім'я
        +плануватиПрем'єру()
        +запуститиЧат()
        +податиАпеляцію()
    }

    class Модератор {
        +String ім'я
        +блокуватиСпам()
        +модеруватиЧат()
        +модеруватиКонтент()
    }

    class Контент {
        +String назва
        +показати()
    }

    Глядач --> Контент
    Автор --> Контент
    Модератор --> Контент
