sequenceDiagram
    participant Глядач
    participant Автор
    participant Модератор
    participant Система

    Глядач->>Автор: Запит на підписку
    Автор->>Система: Підписка на прем'єру
    Система->>Глядач: Підтвердження підписки

    Глядач->>Контент: Перегляд відео
    Автор->>Модератор: Повідомлення про порушення
    Модератор->>Система: Блокування порушення
    Система->>Модератор: Підтвердження блокування
