stateDiagram-v2
    [*] --> Ініціалізація
    
    Ініціалізація --> РеєстраціяКористувачів: CreateSystem()
    
    РеєстраціяКористувачів --> ПублікаціяКонтенту: RegisterUser()
    
    ПублікаціяКонтенту --> ПланюванняПрем_єри: PublishContent()
    
    ПланюванняПрем_єри --> ЗапускЧату: SchedulePremiere()
    
    ЗапускЧату --> ВзаємодіяГлядачів: StartChat()
    
    ВзаємодіяГлядачів --> Підписка: InitializeViewers()
    
    Підписка --> ПереглядВідео: Subscribe()
    
    ПереглядВідео --> КоментуванняВідео: WatchContent()
    
    КоментуванняВідео --> МодеріацаКонтенту: CommentOnContent()
    
    МодеріацаКонтенту --> БлокуванняСпаму: ModerateChat()
    
    БлокуванняСпаму --> ВидаленняКоментарів: BlockSpam()
    
    ВидаленняКоментарів --> ДемонстраціяПоліморфізму: DeleteInappropriateComment()
    
    ДемонстраціяПоліморфізму --> Апеляція: PerformAction()
    
    Апеляція --> СтатистикаСистеми: SubmitAppeal()
    
    СтатистикаСистеми --> [*]: PrintStatistics()
