@startuml UseCase_CSharp
actor Application as APP
actor Глядач as V
actor Автор as A
actor Модератор as M

rectangle "Система управління прем'єрами" {
    usecase "Реєстрація користувача" as UC1
    usecase "Публікація контенту" as UC2
    usecase "Планування прем'єри" as UC3
    usecase "Запуск чату" as UC4
    usecase "Підписка на прем'єру" as UC5
    usecase "Перегляд відео" as UC6
    usecase "Коментування відео" as UC7
    usecase "Модерація чату" as UC8
    usecase "Блокування спаму" as UC9
    usecase "Видалення неприпустимих коментарів" as UC10
    usecase "Подання апеляції" as UC11
    usecase "Отримання статистики" as UC12
}

APP --> UC1
APP --> UC2
APP --> UC12

V --> UC1
V --> UC5
V --> UC6
V --> UC7

A --> UC1
A --> UC2
A --> UC3
A --> UC4
A --> UC11

M --> UC1
M --> UC8
M --> UC9
M --> UC10

UC1 ..> UC5 : include
UC3 --> UC4
UC4 --> UC8
UC5 --> UC6
UC6 --> UC7
UC7 --> UC9
UC11 --> UC8

@enduml
