@startuml
actor Глядач as G
actor Автор as A
actor Модератор as M

G --> (Підписка на прем'єру)
G --> (Перегляд відео)
G --> (Коментування відео)

A --> (Планування прем'єри)
A --> (Запуск чату)
A --> (Модерація контенту)
A --> (Подання апеляції)

M --> (Блокування спаму)
M --> (Модерація чату)
M --> (Видалення неприпустимих коментарів)

(Підписка на прем'єру) --> (Перегляд відео)
(Запуск чату) --> (Модерація чату)
(Модерація контенту) --> (Модерація чату)
(Подання апеляції) --> (Модерація контенту)

@enduml
